### ISSUE TITLE
'module' object has no attribute 'main'

### ISSUE THREAD

**Issue by IronicFreedom** [Photon-HDF5/phforge#2]
I have created two files "metadata.yaml" and "photon_data.h5". If I now want to make a file out of these two using phforge metadata.yaml photon_data.h5 output.h5 I get this error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\pkg_resources\__init__.py", line 2416, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'phforge' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py35\Scripts\phforge-script.py", line 11, in <module>
    load_entry_point('phforge==0.2', 'console_scripts', 'phforge')()
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\pkg_resources\__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\pkg_resources\__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\pkg_resources\__init__.py", line 2408, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\pkg_resources\__init__.py", line 2418, in resolve
    raise ImportError(str(exc))
ImportError: module 'phforge' has no attribute 'main'

Is this a known error? Being new to Python I'm not so sure as to what that means.

**Comment by tritemio** [comment]
Thanks for reporting this issue!

 I was able to reproduce it on a windows machine and I pushed a fix in commit 2d4dbc745501b757c9eb52c70b7feec9f4967dfc

You can update phforge via git and install the new version from the source folder:

```
pip install .
```
This should fix the issue. Please let us know.

**Comment by IronicFreedom** [comment]
phforge seems to work now. Thank you!

Just the version in setup.py is still 0.2, though.

**Comment by tritemio** [comment]
@IronicFreedom, good catch! I had forgotten updating the string in setup.py. Now is fixed thanks.
